<?php

    use Tivet\Banner\TeamSpeak\Factory;
    date_default_timezone_set('Asia/Tehran');
    $hour = date('h');
    $min = date('i');
    $hours = $hour - 1;
    $date = date('Y-m-d');

    return [
        'text' => [
            [
                'value'   => "Welcome " . Factory::client()->getClientNickname(),
                'size'    => 22,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#faf7f7',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 61.8,
                'y'       => 240,
            ],
            [
                'value'   => Factory::server()->getServerOnlineClientCount(true) . " / " . Factory::server()->getServerMaxClientLimit() . " Online",
                'size'    => 23,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 70,
                'y'       => 27,
            ],
            [
                'value'   => Factory::server()->getOnlineAdminCount() . " ADMIN",
                'size'    => 20,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 88,
                'y'       => 115,
            ],
            [
                'value'   => Factory::server()->getOnlineSupportCount() . " SUPPORT",
                'size'    => 19,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 88,
                'y'       => 155,
            ],
            [
                'value'   => Factory::server()->getServerTotalPing() . " Ping",
                'size'    => 20,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 225,
                'y'       => 117,
            ],
            [
                'value'   => Factory::server()->getServerTotalPacketLoss() . " % Loss",
                'size'    => 20,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 228,
                'y'       => 155,
            ],
            [
                'value'   => "-WatchDogs-",
                'size'    => 20,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 365,
                'y'       => 140,
            ],
            [
                'value'   => "Welcome To",
                'size'    => 20,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 370,
                'y'       => 90,
            ],
            [
                'value'   => $hours . ":" . $min,
                'size'    => 40,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 600,
                'y'       => 110,
            ],
            [
                'value'   => $date,
                'size'    => 25,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 600,
                'y'       => 160,
            ],
            [
                'value'   => "SORENAFILE.IR",
                'size'    => 22,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#faf7f7',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 670,
                'y'       => 260,
            ],
            [
                'value'   => "-WatchDogs- TS",
                'size'    => 22,
                'font'    => BASE_DIR . '/resources/font/Exo2-Bold.otf',
                'color'   => '#faf7f7',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 660,
                'y'       => 25,
            ],
            [
                'value'   => "v " . Factory::client()->getClientVersion(),
                'size'    => 15,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 400,
                'y'       => 212,
            ],
        ],
    ];